package practice.example.forum.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import practice.example.forum.model.MyFriends;
import practice.example.forum.model.MyFriendsExample;

public interface MyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    long countByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int deleteByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int insert(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int insertSelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    List<MyFriends> selectByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    MyFriends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int updateByExampleSelective(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int updateByExample(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int updateByPrimaryKeySelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    int updateByPrimaryKey(MyFriends record);
}