package practice.example.forum.model;

import java.util.ArrayList;
import java.util.List;

public class MyFriendsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public MyFriendsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMyUserIdIsNull() {
            addCriterion("my_user_id is null");
            return (Criteria) this;
        }

        public Criteria andMyUserIdIsNotNull() {
            addCriterion("my_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyUserIdEqualTo(String value) {
            addCriterion("my_user_id =", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdNotEqualTo(String value) {
            addCriterion("my_user_id <>", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdGreaterThan(String value) {
            addCriterion("my_user_id >", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("my_user_id >=", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdLessThan(String value) {
            addCriterion("my_user_id <", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdLessThanOrEqualTo(String value) {
            addCriterion("my_user_id <=", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdLike(String value) {
            addCriterion("my_user_id like", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdNotLike(String value) {
            addCriterion("my_user_id not like", value, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdIn(List<String> values) {
            addCriterion("my_user_id in", values, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdNotIn(List<String> values) {
            addCriterion("my_user_id not in", values, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdBetween(String value1, String value2) {
            addCriterion("my_user_id between", value1, value2, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyUserIdNotBetween(String value1, String value2) {
            addCriterion("my_user_id not between", value1, value2, "myUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdIsNull() {
            addCriterion("my_friend_user_id is null");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdIsNotNull() {
            addCriterion("my_friend_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdEqualTo(String value) {
            addCriterion("my_friend_user_id =", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdNotEqualTo(String value) {
            addCriterion("my_friend_user_id <>", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdGreaterThan(String value) {
            addCriterion("my_friend_user_id >", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("my_friend_user_id >=", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdLessThan(String value) {
            addCriterion("my_friend_user_id <", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdLessThanOrEqualTo(String value) {
            addCriterion("my_friend_user_id <=", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdLike(String value) {
            addCriterion("my_friend_user_id like", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdNotLike(String value) {
            addCriterion("my_friend_user_id not like", value, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdIn(List<String> values) {
            addCriterion("my_friend_user_id in", values, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdNotIn(List<String> values) {
            addCriterion("my_friend_user_id not in", values, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdBetween(String value1, String value2) {
            addCriterion("my_friend_user_id between", value1, value2, "myFriendUserId");
            return (Criteria) this;
        }

        public Criteria andMyFriendUserIdNotBetween(String value1, String value2) {
            addCriterion("my_friend_user_id not between", value1, value2, "myFriendUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_friends
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 14 21:30:39 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_friends
     *
     * @mbg.generated Mon Feb 14 21:30:39 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}